
package jax.client.services.interfaces;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificationReceiver", targetNamespace = "http://interfaces.services.ws.jax/"/*, wsdlLocation = "http://localhost:92/DigitalSignerNotificaciones/NotificationReceiver?WSDL"*/)
public class NotificationReceiver
    extends Service
{

    private final static URL NOTIFICATIONRECEIVER_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONRECEIVER_EXCEPTION;
    private final static QName NOTIFICATIONRECEIVER_QNAME = new QName("http://interfaces.services.ws.jax/", "NotificationReceiver");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            // CAMBIAR URL POR LA PROPIEDAD CORRESPONDIENTE EN FUNCION DE LA CONFIGURACION
            url = new URL("http://localhost:92/DigitalSignerNotificaciones/NotificationReceiver?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONRECEIVER_WSDL_LOCATION = url;
        NOTIFICATIONRECEIVER_EXCEPTION = e;
    }

    public NotificationReceiver() {
        super(__getWsdlLocation(), NOTIFICATIONRECEIVER_QNAME);
    }

    public NotificationReceiver(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONRECEIVER_QNAME, features);
    }

    public NotificationReceiver(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONRECEIVER_QNAME);
    }

    public NotificationReceiver(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONRECEIVER_QNAME, features);
    }

    public NotificationReceiver(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationReceiver(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificationReceiverImpl
     */
    @WebEndpoint(name = "NotificationReceiverImplPort")
    public NotificationReceiverImpl getNotificationReceiverImplPort() {
        return super.getPort(new QName("http://interfaces.services.ws.jax/", "NotificationReceiverImplPort"), NotificationReceiverImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationReceiverImpl
     */
    @WebEndpoint(name = "NotificationReceiverImplPort")
    public NotificationReceiverImpl getNotificationReceiverImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interfaces.services.ws.jax/", "NotificationReceiverImplPort"), NotificationReceiverImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONRECEIVER_EXCEPTION!= null) {
            throw NOTIFICATIONRECEIVER_EXCEPTION;
        }
        return NOTIFICATIONRECEIVER_WSDL_LOCATION;
    }

}
